## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('train.csv')

In [10]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [11]:
df.shape

(20800, 5)

In [12]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [13]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [14]:
###Drop Nan Values
df=df.dropna()


In [15]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [16]:
df.shape

(18285, 5)

In [17]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [18]:
## Get the Dependent features
y=df['label']

In [19]:
X.shape

(18285, 4)

In [20]:
y.shape

(18285,)

In [21]:
import tensorflow as tf

In [22]:
tf.__version__

'2.18.0'

In [23]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [24]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [25]:
messages=X.copy()

In [26]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [27]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [28]:
messages.reset_index(inplace=True)

In [29]:
messages.head(30)

index  id                                              title  \
0       0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1       1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2       2   2                  Why the Truth Might Get You Fired   
3       3   3  15 Civilians Killed In Single US Airstrike Hav...   
4       4   4  Iranian woman jailed for fictional unpublished...   
5       5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6       7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
7       9   9  A Back-Channel Plan for Ukraine and Russia, Co...   
8      10  10  Obama’s Organizing for Action Partners with So...   
9      11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   
10     12  12  Russian Researchers Discover Secret Nazi Milit...   
11     13  13  US Officials See No Link Between Trump and Russia   
12     14  14  Re: Yes, There Are Paid Government Trolls On S...   
13     15  15  In Major League Soccer, Argentines Find a Home...   
14     16  16  Wells Fargo Chief Abruptly Steps Down - The Ne...   
15     17  17  Anonymous Donor Pays $2.5 Million To Release E...   
16     18  18                          FBI Closes In On Hillary!   
17     19  19  Chuck Todd: ’BuzzFeed Did Donald Trump a Polit...   
18     21  21  Monica Lewinsky, Clinton Sex Scandal Set for ’...   
19     22  22  Rob Reiner: Trump Is ’Mentally Unstable’ - Bre...   
20     24  24  Abortion Pill Orders Rise in 7 Latin American ...   
21     25  25  Nukes and the UN: a Historic Treaty to Ban Nuc...   
22     26  26  EXCLUSIVE: Islamic State Supporters Vow to ‘Sh...   
23     27  27  Humiliated Hillary Tries To Hide What Camera C...   
24     28  28  Andrea Tantaros of Fox News Claims Retaliation...   
25     29  29  How Hillary Clinton Became a Hawk - The New Yo...   
26     30  30  Chuck Todd to BuzzFeed EIC: ’You Just Publishe...   
27     32  32  Having Won, Boris Johnson and ‘Brexit’ Leaders...   
28     33  33  Texas Oil Fields Rebound From Price Lull, but ...   
29     34  34  Bayer Deal for Monsanto Follows Agribusiness T...   

                                               author  \
0                                       Darrell Lucus   
1                                     Daniel J. Flynn   
2                                  Consortiumnews.com   
3                                     Jessica Purkiss   
4                                      Howard Portnoy   
5                                     Daniel Nussbaum   
6                                     Alissa J. Rubin   
7                        Megan Twohey and Scott Shane   
8                                         Aaron Klein   
9                                     Chris Tomlinson   
10                                      Amando Flavio   
11                                         Jason Ditz   
12                                       AnotherAnnie   
13                                      Jack Williams   
14                   Michael Corkery and Stacy Cowley   
15                                           Starkman   
16                                            The Doc   
17                                          Jeff Poor   
18                                      Jerome Hudson   
19                                            Pam Key   
20               Donald G. McNeil Jr. and Pam Belluck   
21                                        Ira Helfand   
22                          Aaron Klein and Ali Waked   
23                                        Amanda Shea   
24                                          Jim Dwyer   
25                                       Mark Landler   
26                                       Ian Hanchett   
27                                    Steven Erlanger   
28                                    Clifford Krauss   
29  Leslie Picker, Danny Hakim and Michael J. de l...   

                                                 text  
0   House Dem Aide: We Didn’t Even See Comey’s Let...  
1   Ever get th

In [30]:
import nltk
import re
from nltk.corpus import stopwords

In [31]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [32]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [33]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [34]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [35]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[2087, 3484, 4887, 2998, 4308, 2275, 1128, 3200, 706, 4978],
 [1325, 1067, 4181, 1063, 70, 2384, 3272],
 [2162, 4254, 4975, 2826],
 [2521, 2954, 3304, 1744, 4575, 1489],
 [2325, 70, 1001, 2919, 3804, 2104, 70, 1055, 2277, 2070],
 [4029,
  1818,
  2323,
  933,
  1774,
  2296,
  1953,
  4778,
  3999,
  2382,
  59,
  3162,
  4004,
  1724,
  3272],
 [1846, 3168, 713, 2085, 2841, 4303, 4627, 3704, 2030, 907, 4237],
 [668, 4842, 3310, 2017, 1527, 769, 2296, 198, 2030, 907, 4237],
 [1292, 4534, 1891, 3598, 3874, 2421, 4008, 1754, 2296, 4368],
 [2365, 2448, 331, 3857, 597, 1796, 1122, 1294],
 [4196, 2224, 739, 754, 1452, 4384, 475, 4439, 1864, 1245, 3545],
 [1744, 3409, 4308, 2421, 2296, 1527],
 [2375, 1157, 2070, 1396, 4121, 742, 603, 2733, 2175],
 [2465, 439, 4404, 4436, 1888, 1056, 207, 2030, 907, 4237],
 [4429, 4481, 391, 4751, 2191, 2030, 907, 4237],
 [1673, 439, 2512, 3229, 33, 1600, 1078, 2239, 3154, 488],
 [4500, 3868, 1067],
 [3035, 401, 2497, 1851, 2296, 3821, 4010, 3272],
 [2578, 4

In [36]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [37]:
onehot_repr[1]

[1325, 1067, 4181, 1063, 70, 2384, 3272]

### Embedding Representation

In [38]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[2087 3484 4887 ...    0    0    0]
 [1325 1067 4181 ...    0    0    0]
 [2162 4254 4975 ...    0    0    0]
 ...
 [4445 1337  597 ...    0    0    0]
 [ 692 1527 2185 ...    0    0    0]
 [ 352 2838 4209 ...    0    0    0]]


In [39]:
embedded_docs[1]

array([1325, 1067, 4181, 1063,   70, 2384, 3272,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [40]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_shape=(sent_length,)))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 20, 40)              │         200,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 100)                 │          56,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [41]:
len(embedded_docs),y.shape

(18285, (18285,))

In [42]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [43]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [45]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7751 - loss: 0.4121 - val_accuracy: 0.9231 - val_loss: 0.1882
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9523 - loss: 0.1319 - val_accuracy: 0.9296 - val_loss: 0.1879
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9673 - loss: 0.0962 - val_accuracy: 0.9223 - val_loss: 0.2421
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.9821 - loss: 0.0563 - val_accuracy: 0.9193 - val_loss: 0.2071
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9898 - loss: 0.0421 - val_accuracy: 0.9162 - val_loss: 0.2457
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9925 - loss: 0.0317 - val_accuracy: 0.9183 - val_loss: 0.3285
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9923 - loss: 0.0259 - val_accuracy: 0.9157 - val_loss: 0.3091
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9936 - loss: 0.0245 - val_accuracy: 0

### Performance Metrics And Accuracy

In [46]:
y_pred=model.predict(X_test)

189/189 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [47]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [48]:
from sklearn.metrics import confusion_matrix

In [49]:
confusion_matrix(y_test,y_pred)

array([[3152,  267],
       [ 261, 2355]])

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9125103562551782

In [51]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3419
           1       0.90      0.90      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

